const workArray = [
  `you walked and won [money] agnabucks because you ate lasanga :   )`,
  `dace broke into your house and gave you [money] agnabucks. and then ate your food XDDDDDDDDDDDDDDDD`,
  `我非常喜歡食物，所以我給了你 [money] 個“Agnabucks”來解決你的麻煩`,
  `you opened your mail today and saw [money] agnabucks just laying there, lucky you!`,
  `you went to the casino and cashed in on [money] agnabucks`,
  `FUCK YOU HERES [money] AGNABUCKS GO DIE A PAINFUL DEATH`,
  `[money]`,
  `you went to a furcon and won [money] agnabucks because Box loved your outfit`,
  `You worked and got [money] agnabucks. Eat it. Eat it. Eat it. Eat it. Eat it. Eat it. Eat it. Eat it.`,
  `You almost died in Silon Fighting but somehow survived and got rewarded [money] agnabucks for your troubles.`,
  `I'm Spongebob! I'm [money] Agnabucks! I'm Spongebob!`,
  `BTS IS COMING! [money] AGNABUCKS BY BTS! THE AGNABUCKS ARE COMING!`,
  `JapaMoney 🤑 Japanese money, [money] Agnabucks Money Bambu.`,
  `nice of the princess to invite us over to a picnic, ey luigi? i hope she gives us [money] agnabucks!`,
  `happy birthday to you happy birthday to you happy birthday [money] agnabucks happy birthday to you`,
  `Fun fact: in 1875, someone in the Agnab's Amassing Discord Server won [money] Agnabucks by simply saying \`a.work\`.. How shocking!`,
  `the enconomy is in shambles but you just won [money] agnabucks so you dont care`,
  `YOU ARE OUR [1 MILLIONTH] WORKER! CLAIM YOUR PRIZE OF [[money] AGNABUCKS] NOW!`,
  `agnab is extremely fucking stupid and accidentally wired you [money] agnabucks.`,
  `you found [money] agnabucks on top of a volcano HOW TF DID YOU EVEN GET THER`,
  `you spent 15 dollars on anal lube and got [money] agnabucks from your onlyfans (you are fucking disgusting)`,
  `you started streaming for cherity but you took [money] agnabucks for yourself you monster`,
  `potato casserole. [money] agnabucks. [money] [money] [money] [money] [money] [money][money][money][money][money][money][money][money][money][money][money][money][money][money][money][money][money][money][money][money]`,
  `thank you Two THirty for these cool work texxtsss here is your [money]`,
  "You worked a lemonade stand. You got [money] agnabucks somehow. Fucking ripping people off, asshole",
  "Shhh, don't tell Agnab, but I stole [money] bucks from him... 🤫",
  "I heard you were broke, you broke bitch, have [money] agnabucks.",
  "[money] : ) I really love [money]",
  "Halo bambi sucks, so you stole [money] bucks from him",
  "**Death...** **DEATH!!!** Huh? Oh, here's [money] agnabucks.",
  "I had someone tell me I [money] 'd off. OOH I needed that 😏💯💯",
  "Real All About Me! by the one and only [money] !",
  "PUSSY BITCH WOWWOISSKDMA[money]EEEE!!!",
  "You work at borgur jointf, gain [money] mony : )",
  "Screamed at little kids, gained [money] agnabucks",
  "Hello, it is me, Jesus. Have [money] agnabucks",
  "This dude really be typing a.work to get a virtual currency with no value in life, imagine that. Anyways, here's [money] agnabucks.",
  "You destroyed an atm and recieved [money] bucks.",
  "Imagine you got this, 64 , [money] , 66. That would be fucking sick, I think.",
  "Keep on keeping bucking your agnab's! +[money]!",
  "Gren lef. HAT ⨊⨊ [money] ⨇",
  "If you got this, make a song with this bpm: [money]",
  "🎎[money]🎎🎎[money]🎎🎎[money]🎎🎎[money]🎎",
  "YOU ARE [money] years old",
  "Shut up and take [money] bucks!",
  "Did you know, that [money] equals [money]? Crazy right?",
  "Discrimination! [money]! Discrimination! [money]!",
  "You stole [money] bucks from Baby Hortas!",
  "You crossed the street, and got [money] agnabucks. I wish it were that easy...",
  "Make sure to follow the #rules ! Heres [money] bucks for listening.",
  "Yo okay, they call me [money] I'm rob store and drink coke.",
  "🧜‍♂️[money]🧜‍♀️",
];

module.exports = { workArray }